---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
# - name: greeting
#   image: alpine
#   commands:
#   - echo hello
#   - echo build

- name: frontend
  image: node
  volumes:
  - name: dist
    path: /host-dist
  commands:
  - npm install
  - npm run build
  - rm -rf /host-dist/* && cp -r ./out/* /host-dist

trigger:
  branch:
  - main

volumes:
- name: dist
  host:
    path: /var/lib/drone/project-pim