---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo build

- name: frontend
  image: node
  commands:
  - npm install
  - npm export