---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
# - name: greeting
#   image: alpine
#   commands:
#   - echo hello
#   - echo build

- name: frontend
  image: node
  volumes:
  - name: dist
    path: /dist
  commands:
  - npm install
  - npm run export
  - cp -r ./out /dist

volumes:
- name: dist
  host:
    path: /var/lib/pim-out